augment: 0
batch_size: 8
best_k: 10
centered: 1
cfg: configs/Univ_sgan3A.py
checkpoint_every: 10
checkpoint_name: checkpoint
checkpoint_start_from: null
clipping_threshold_d: 0
clipping_threshold_g: 0
conn_dist: 100000.0
d_learning_rate: 0.0001
d_steps: 2
data_root_ethucy: datasets/eth_ucy
dataset: eth
dec_layers: 2
enc_layers: 2
forecast_dim: 2
frame_skip: 1
future_frames: 12
g_learning_rate: 0.0001
g_steps: 1
gpu_num: '0'
input_type: pos
k: 1
kl_weight: 1.0
l2_loss_weight: 1.0
min_future_frames: 12
min_past_frames: 8
motion_dim: 2
noise_std: 0.0
num_epochs: 100
num_samples_check: 500
nz: 32
output_dir: /Users/dannychiang/Desktop/TAMU/CSCE689_MRS/project/sgan3A
past_frames: 8
phase: training
pos_concat: true
print_every: 50
restore_from_checkpoint: 0
resume_warmup_from: null
scheduler_factor: 0.5
scheduler_gamma: null
scheduler_min_lr: 0
scheduler_patience: 10
scheduler_step_size: null
scheduler_type: none
tf_dropout: 0.1
tf_ff_dim: 512
tf_model_dim: 256
tf_nhead: 8
traj_scale: 1
use_cvae: 0
use_gpu: 1
warmup_epochs: 3
z_type: gaussian
